# Main program : analysis of SI_clean.csv

In [5]:
import pandas as pd

df = pd.read_csv("data/SI_clean.csv", delimiter=";", encoding="utf-8")

df

,janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre
0,-5,-7.0,-7,2.0,12,17.0,20,20,16.0,6,0.0,-6
1,-6,-6.0,-8,3.0,14,16.0,20,19,14.0,2,1.0,-4
2,-5,-5.0,-5,4.0,15,17.0,17,19,15.0,3,2.0,-8
3,-3,-6.0,-3,6.0,16,14.0,18,18,13.0,4,3.0,-9
4,-6,-8.0,-2,4.0,13,15.0,17,17,12.0,3,4.0,-9
5,-11,-9.0,1,5.0,12,17.0,17,18,10.0,2,3.0,-9
6,-6,5.0,2,4.0,8,17.0,16,16,12.0,4,4.0,-8
7,-8,-11.0,1,6.0,7,15.0,17,17,11.0,5,5.0,-4
8,-11,-12.0,1,7.0,6,14.0,17,15,11.0,3,5.0,-3
9,-8,-9.0,2,7.0,5,15.0,15,14,12.0,4,-1.0,-8
10,-8,-6.0,1,8.0,5,14.0,15,14,10.0,2,-2.0,-9
11,-8,-5.0,3,8.0,6,13.0,16,15,10.0,1,-1.0,-5
12,-8,-4.0,5,9.0,8,11.0,16,15,9.0,3,-7.0,-6
13,-10,1.0,5,10.0,10,14.0,13,15,9.0,3,-8.0,-7
14,-10,3.0,7,8.0,12,15.0,14,17,10.0,3,-5.0,-11
15,-9,-9.0,3,8.0,13,15.0,14,18,11.0,1,-3.0,-6
16,-6,-6.0,2,9.0,14,15.0,15,19,10.0,4,-2.0,-8
17,-6,-6.0,-1,11.0,13,17.0,15,21,10.0,6,1.0,-11
18,-4,-4.0,-2,10.0,15,16.0,15,24,9.0,6,2.0,-8
19,-8,2.0,-1,11.0,15,19.0,17,21,11.0,6,1.0,-8
20,-9,3.0,0,12.0,15,20.0,18,21,12.0,7,0.0,-3
21,-14,1.0,1,9.0,18,19.0,19,26,12.0,7,0.0,-6
22,-15,-3.0,2,7.0,18,20.0,21,17,10.0,6,1.0,-8
23,-17,-4.0,3,8.0,16,22.0,24,18,11.0,6,3.0,-9
24,-19,-6.0,4,8.0,15,22.0,23,17,10.0,6,5.0,-5
25,-23,-8.0,3,6.0,16,21.0,26,17,9.0,4,-2.0,-6
26,-8,-8.0,4,9.0,16,22.0,26,16,6.0,3,-3.0,-7
27,-9,-11.0,5,11.0,17,21.0,21,17,7.0,3,-6.0,-8
28,-5,NaN,5,14.0,16,21.0,22,17,7.0,4,-6.0,-6
29,-6,NaN,3,16.0,17,17.0,23,18,6.0,2,-4.0,-7
30,-7,NaN,3,NaN,17,NaN,21,17,NaN,1,NaN,-5

## Moyenne de température par mois

In [6]:
df.mean()

janvier      -8.967742
février      -4.928571
mars          1.193548
avril         8.000000
mai          12.903226
juin         17.033333
juillet      18.322581
août         17.838710
septembre    10.500000
octobre       3.870968
novembre     -0.333333
décembre     -7.000000
dtype: float64

## Minimum de température par mois

In [14]:
df.min()

janvier     -23.0
février     -12.0
mars         -8.0
avril         2.0
mai           5.0
juin         11.0
juillet      13.0
août         14.0
septembre     6.0
octobre       1.0
novembre     -8.0
décembre    -11.0
dtype: float64

## Minimum de température dans l'année

In [15]:
df.min().min()

-23.0

## Maximum de température par mois

In [8]:
df.max()

janvier      -3.0
février       5.0
mars          7.0
avril        16.0
mai          18.0
juin         22.0
juillet      26.0
août         26.0
septembre    16.0
octobre       7.0
novembre      5.0
décembre     -3.0
dtype: float64

## Maximum de température dans l'année

In [15]:
df.min().min()

-23.0

## Ecart type de température par mois

In [9]:
df.std()

janvier      4.490611
février      4.561746
mars         3.506369
avril        3.151354
mai          4.036127
juin         3.011281
juillet      3.571994
août         2.696872
septembre    2.330458
octobre      1.802627
novembre     3.717000
décembre     2.065591
dtype: float64